name: Build and push Docker image to GitHub Package Registry

on:
    workflow_call:
        inputs:
            registry:
                description: Remote registry to push the Docker image to
                default: ghcr.io
                required: false
                type: string
            ghub_repository:
                description: GitHub repository to push the Docker image to
                default: amexei/angular-react-starter
                required: false
                type: string

jobs:
    build-push-docker:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: angular

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ inputs.registry }}
                  username: ${{ github.actor }}
                  password: ${{ github.token }}

            - name: Preparing Docker tags
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ inputs.registry }}/${{ secrets.GHUB_REPOSITORY }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}

            - name: Calculate Steps Log Time
              if: always()
              id: duration
              uses: RockyIsHere/actions-calculate-log-time@v0.2.4
              env:
                  GITHUB_TOKEN: ${{ github.token }}
